// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeuZwexT77MxAzy8Fczhr4SB8PITG1m4E',
    appId: '1:905646284499:web:bf5e2b7e468d91a726be26',
    messagingSenderId: '905646284499',
    projectId: 'webrtc-app-ac',
    authDomain: 'webrtc-app-ac.firebaseapp.com',
    storageBucket: 'webrtc-app-ac.appspot.com',
    measurementId: 'G-92PLEHL0DR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyRw4m_wIE2FQt5LVdhIFN68xDNEkzILQ',
    appId: '1:905646284499:android:b62326ae63f8b48b26be26',
    messagingSenderId: '905646284499',
    projectId: 'webrtc-app-ac',
    storageBucket: 'webrtc-app-ac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlwYImEAzzksLwJeLpugzjQ39kPPUb0lE',
    appId: '1:905646284499:ios:ac04c01019d2a8f226be26',
    messagingSenderId: '905646284499',
    projectId: 'webrtc-app-ac',
    storageBucket: 'webrtc-app-ac.appspot.com',
    iosBundleId: 'com.example.applicationWebrtc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlwYImEAzzksLwJeLpugzjQ39kPPUb0lE',
    appId: '1:905646284499:ios:0e9b00fe78ff604626be26',
    messagingSenderId: '905646284499',
    projectId: 'webrtc-app-ac',
    storageBucket: 'webrtc-app-ac.appspot.com',
    iosBundleId: 'com.example.applicationWebrtc.RunnerTests',
  );
}
